### ISSUE TITLE
Validación offer

### ISSUE THREAD

**Issue by sanframar** [rafgardom/ISPP-Makai#1]
Cuando se acepta una Offer se debe de eliminarla relación entre Animal y AnimalShelter y en su lugar crear la relación entre Customer y Animal.

**Comment by rafgardom** [comment]
Podemos hacer eso o directamente mantener la relacion de animal con animalShelter y crear la nueva con customer para saber que ese animal venia de una protectora.
Lo que os parezca mejor

**Comment by sanframar** [comment]
Finalmente se ha decidido mantener la relación para saber de que protectora viene el animal.
