### ISSUE TITLE
Contraseñas débiles

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#10]
No existe ningún tipo de restricción a la hora de validar contraseñas. Esto puede ser un problema desde el punto de vista de la seguridad ya que un ataque de diccionarios puede calcular contraseñas débiles en cuestión de segundos. 
Se recomienda usar algún tipo de condición necesaria para dar por válida una contraseña. 
Posible solución: [https://stackoverflow.com/questions/5142103/regex-to-validate-password-strength](url)

**Comment by dierodfer** [comment]
si se llega a implementar esto, porfavor dejar un usuario de cada tipo sin contraseña o muy fácil para el testeo

**Comment by rafgardom** [comment]
Ya se ha corregido. Ahora las contraseñas requieren que cumplan el siguiente patrón:
                       ((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{6,30}) 

Una contraseña ahora debe contar con caracteres especiales, numeros y mayusculas)

Para facilitar las pruebas los usuarios creados por defecto en el populate tienen la misma contraseña que el username
