### ISSUE TITLE
¿Viajes con un máximo de 20 horas?

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#100]
Uno de los nuevos cambios que se han hecho en la vista de viajes ha sido colocar una barra para determinar la duración del viaje durante la creación de uno nuevo. 
Este nuevo elemento, desde el punto de vista visual es muy bueno, pero desde mi punto de vista, estamos limitando la usabilidad de la aplicación. ¿Que pasa si quiero enviar mi perro desde Sevilla a Berlín en coche y el viaje es de 2 días? (es un caso extremo y rara vez se va a dar, pero cabe la posibilidad de que suceda).
Yo propongo o bien dejarlo como estaba antes, con campos númericos o bien hacer una combinación de las 2 soluciones, es decir, dejar la barra de tiempo para los minutos, segundos y horas (ampliando hasta las 23 horas), y añadir un campo númerico donde el usuario pueda insertar los días.

**Comment by dierodfer** [comment]
Temporalmente se amplió a 23 horas. Se añadirá otra barra para añadir días.
