### ISSUE TITLE
Validación incorrecta de imagen al registrar animal

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#101]
Cuando intentamos registrar un nuevo animal, si insertamos como imagen un fichero no permitido, la aplicación no muestra ningún error y crear la nueva entrada sin problemas (la prueba que he realizado ha sido con un fichero .project).

Pasa lo mismo en la modificación de animal.

Esta prueba ya se realizó hace tiempo y tuvo un resultado satisfactorio. **Se ruega revisar el resto de pruebas relacionadas con "Animal" cuando se hace algún cambio en esta parte del código** (Hoja "Animal" del documento excel de pruebas).

**Comment by shelux** [comment]
Se ha corregido el formato de imagen permitido, tanto para tamaño como para tipo de archivo
