### ISSUE TITLE
Eliminación en paralelo de animal

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#103]
Si listamos todos los animales de un mismo usuario desde dos ventanas distintas (una de ellas privada) y luego eliminamos un animal desde una de las ventanas, la aplicación permite:
- Eliminar ese mismo animal desde la otra ventana.
- Visualizar ese mismo animal ya eliminado desde la otra ventana.
- Modificar ese mismo animal ya eliminado desde la otra ventana.

Se debería de mostrar un mensaje de error cuando se intenta realizar alguna de estas acciones sobre un animal ya eliminado (y que se sobreentiende que no debería existir en la aplicación).

**Comment by shelux** [comment]
Se ha controlado tanto en el controlador como en el servicio que el animal esté eliminado (isHidden) para que no se produzca ese problema.
