### ISSUE TITLE
Sin limite de tamaño de imagen al crear animal

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#107]
Si intentamos crear un animal, al cargar una imagen, podemos elegir una con tamaño mayor a 5 MB.

Además, las imagenes no se ven correctamente al listar los animales.
![imagen](https://user-images.githubusercontent.com/10712481/39007134-5ed27c38-4405-11e8-813d-34ed1a8fcf8f.png)

**Comment by shelux** [comment]
Se ha establecido que el tamaño de las imágenes sea de 2MB
