### ISSUE TITLE
No se puede iniciar sesión Paypal

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#108]
Al intentar hacer un pago, si intento acceder a mi cuenta de paypal, aún insertando correctamente los credenciales, me aparece que los datos son incorrectos.

![imagen](https://user-images.githubusercontent.com/10712481/39008005-b53d2ee0-4407-11e8-9026-27ddce0dec38.png)

**Comment by rafgardom** [comment]
No se puede porque actualmente está en modo sandbox

**Comment by rafgardom** [comment]
Habilitada cuenta para sandbox y comprobado que el modo live funciona
