### ISSUE TITLE
No se eliminan los tratos ya finalizados

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#111]
Tras aceptar una oferta, si avanzamos el reloj del sistema hasta una fecha posterior a la de finalización de la oferta, vemos que la aplicación no elimina los tratos ya finalizados.
La prueba que he realizado ha sido:
- He creado una solicitud
- He enviado una oferta ha esa solicitud con la fecha de inicio más próxima posible (el día siguiente al actual) y he puesto como duración todo a 0.
- He aceptado la oferta
- He modificado la hora del sistema a una fecha posterior a la de finalización (en la MV se necesitan permisos especiales, pero realmente la MV coge la hora del sistema operativo host, por lo que si cambias la hora en el ordenador normal, tambien se cambia en la MV).

Tal y como esta ahora implementado la aplicación, la lista de tratos crece hasta el infinito. Yo propongo un par de posibles soluciones:
1. Dar la opción al usuario de eliminar un trato cuando ya ha finalizado (habilitar el botón cuando aún no haya sido aceptada o cuando ya haya finalizado).
2. Que la aplicación elimine automaticamente cada X tiempo todos los tratos finalizados (con un demonio o algún tipo de tarea programada).

Sea cual sea la solución, deberiamos de almacenar durante un tiempo razonable los tratos finalizados (¿6 meses?,¿1 año?), de tal modo que si lo desea, el usuario puede acceder al histórico de tratos finalizados por si desea consultar algún dato. Sin embargo, esta lista de tratos finalizados no debería aparecer en la lista de tratos vigentes, por lo que propongo habilitar algún tipo de botón que lleve al usuario a una lista donde pueda ver y eliminar los tratos finalizados en el últimos meses y/o años.

**Comment by rafgardom** [comment]
Yo propongo una tercera opción y es la de listar en otra lista a parte los tratos ya finalizados. El adiestramiento de media puede durar años así que mínimo debería listar el de los últimos 10 años por ejemplo.
Lo que no es viable es eliminar los tratos que han transcurrido porque nosotros a nivel interno debemos tener un histórico permanente de todo lo que ocurre en la aplicación.

**Comment by sanframar** [comment]
Se ha creado una nueva vista en la cual aparecen las ofertas aceptadas y que han finalizado.
