### ISSUE TITLE
Error al eliminar una raza

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#118]
Desde el rol de admin, si intentamos eliminar una raza o una especie que ya esta por defecto en la aplicación, nos aparece un mensaje de error:
![imagen](https://user-images.githubusercontent.com/10712481/39087027-680e51e6-459a-11e8-9b51-499e30a41524.png)

**Comment by jesvazarg** [comment]
Ahora cuando no se puede borrar una especie ya no sale el boton
