### ISSUE TITLE
Problemas con la codificación en los registros

### ISSUE THREAD

**Issue by rafgardom** [rafgardom/ISPP-Makai#12]
Si introducimos caracteres especiales tipo "ñ" la validación de userAccount falla.

**Comment by gh-jvr** [comment]
El problema sigue existiendo. Cuando se introduce una 'ñ' en la contraseña, la aplicación la detecta como contraseña incorrecta.

**Comment by rafgardom** [comment]
Esto ocurre porque la codificación que utiliza Spring no acepta caracteres especiales tanto para username como para la contraseña. En versiones nuevas de Spring se soluciona pero con la actual la única forma que he encontrado es obligando al usuario a no utilizar ese tipo de caracteres. Lo investigaré más a fondo a ver si se puede corregir
