### ISSUE TITLE
Imagen de banner poco eficiente

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#120]
Desde el rol de admin, si accedemos a un banner para visualizarlo, la imagen del banner aparece enmarcado en un circulo. Este tipo de marcos esta bien para el resto de imagenes de la aplicación, pero al hablar de banner, la imagen es el pilar principal, y no deberíamos de recortarla ni enmarcarlas de ninguna forma, ya que no apreciariamos bien el banner a publicar.

![imagen](https://user-images.githubusercontent.com/10712481/39087430-1e627728-45a1-11e8-95b9-4ba2e85028ec.png)

**Comment by dierodfer** [comment]
Solucionado se quito el efecto que redondeaba las imagenes
