### ISSUE TITLE
Mejora en el acceso a la creación de cuentas

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#122]
Si accedemos a la aplicación con la intención de anunciarnos (crear banners), tenemos 2 formas de llegar a un mismo punto. O bien pulsamos en "Publicítate" y le damos a que "no" tenemos cuenta, o bien desplegamos las opciones de "Registrarse" y pulsamos en "Anunciante".
Desde mi punto de vista, esto es un poco lioso para el usuario, además de tener información duplicada. 
Propongo eliminar la opción "Anunciante" del botón "Registrarse" ya que el perfil de anunciante es poco común y debería de diferenciarse del resto de perfiles.

Además, yo cambiaría la palabra "Registrarse" e "iniciar sesión" por "Registrate" e "inicia sesión", o bien cambiar la palabra del botón "Publicítate" por "publicitarse". La idea es poner en común la forma en la que nos dirigimos al usuario.

**Comment by dierodfer** [comment]
Se elimino la pestaña ''Registrate'' por completo y se añadieron los enlaces en el inicio
