### ISSUE TITLE
No se puede modificar un Banner

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#125]
Desde el perfil de anunciante, si accedemos a la lista de banners, no tenemos la opción de modificar el banner.

Unicamente me ha aparecido la opción de editar con el banner que inserta el populate, pero no con los 
banners creado por mi. He generado los 3 posibles estados de un banner, y en ningún caso aparecía la opción
![imagen](https://user-images.githubusercontent.com/10712481/39144583-7ba11840-4731-11e8-9a3a-72de8e815ceb.png)

**Comment by rafgardom** [comment]
Indicar que el anuncio sólo se podrá modificar cuando el administrador haya validado el anuncio o cuando se encuentre en funcionamiento, es decir, cuando esté pagado.

**Comment by martus13** [comment]
Se ha añadido un mensaje indicando en que caso se puede editar un banner.
