### ISSUE TITLE
Error al validar imagen durante modificación de perfil

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#128]
Durante la modificación de un perfil de usuario, si cargamos un fichero como si fuese una imagen, la aplicación no valida si el formato es el correcto, y almacena lo que se le pase.
Yo he probado con un fichero .txt y lo ha almacenado sin problemas.

**Comment by martus13** [comment]
Arreglado en el commit 6e99830eebd5daa2fc134305a9fb4772123301c7
