### ISSUE TITLE
Acceso por URL a info no permitida

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#129]
Si abrimos 2 ventanas del navegador (una de ellas en modo privado) y nso registramos en la palicación con usuarios distintos, nos damos cuenta que podemos acceder a información de otros usuarios que no debería de permitirse.

**Bug 1:** **Solucionado**
> Ventana 1: Admin  -  Ventana 2: Customer
> Si accedemos a un banner desde admin y copiamos la URL, al copiarla en la ventana de customer, podemos acceder a toda la información del banner de otros usuarios. 
> Esto no se debería permitir porque estariamos dando pie a que empresas tengan acceso a información privada de la competencia.
> Esto mismo pasa también entre cualquier par de roles, no solo entre admin y customer.

**Bug 2:**
> Ventana 1: Customer1  -  Ventana 2: Customer2
> Si accedemos a un animal de customer 1 y copiamos la URL, podemos acceder a ese animal desde customer 2.

**Bug 3:**  **Solucionado**
> Ventana 1: Customer1  -  Ventana 2: Customer2
> Si accedemos a un viaje realizado en el pasado (Mis viajes pasados) de customer 1 y copiamos la URL, podemos acceder a ese viaje desde customer 2.

**Bug4:**  **Solucionado**
> Ventana 1: Customer1  -  Ventana 2: Customer2
> Si accedemos a una notificación única de customer1 (customer2 no tiene esa notificación) y copiamos la URL, podemos pegarla en la sesión de customer2 y acceder a dicha notificación.
> Esto mismo pasa también entre cualquier par de roles, no solo entre admin y customer.

**Bug5:** **Solucionado**
> Ventana 1: Trainer2  -  Ventana 2: Trainer2
> Si accedemos a la modificación de una oferta desde el rol de trainer1, copiamos la URL, nos dirigimos a la ventana de trainer2 y pegamos la url, tenemos acceso a la info de la oferta del otro trainer. Además de podemos ver los datos de otros entrenadores (otros competidores), podemos modificar las ofertas de otros entrenadores (aunque aparezca un error, los cambios se persisten).

**Bug6:**
> Ventana 1: Animalshelter1  -  Ventana 2: Animalshelter2
> Si accedemos a un animal registrado por Animalshelter1, copiamos la URL y la pegamos en la ventana de Animalshelter2, podemos acceder a los datos del animal.

**Bug7:** **Solucionado**
> Ventana 1: Professional1  -  Ventana 2: professional2
> Si accedemos a la modificación de un viaje de professional1, copiamos la URL y la pegamos en la sesión de professional2, podemos ver y modificar los datos del viaje creado por el professional1.
> Lo mismo sucede si accedemos a la visualización del viaje.

**Bug8:** **Solucionado**
> Ventana 1: Professional1  -  Ventana 2: professional2
> Si accedemos a la modificación de un vehiculo de professional1, copiamos la URL y la pegamos en la sesión de professional2, podemos ver y modificar los datos del vehiculo creado por el professional1.

Por favor, revisar el acceso a la información de cada vista de la aplicación, y controlad que solo el usuario logeado pueda acceder a esa vista (siempre que sea posible implementar tal restricción).

**Comment by rafgardom** [comment]
Hay que comprobar no solo que el logueado es un customer, sino que ese customer es el dueño de la informacion a visualizar

**Comment by martus13** [comment]
El bug1 se solucionó en un commit anterior, se ha quitado la vista de display de banner, ahora solo se muestra la imagen.
