### ISSUE TITLE
Número de notificación nunca desaparece

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#13]
Cuando se entra en la plataforma, aparece un número de notificaciones en rojo al lado "Notificaciones" de la toolbar de arriba. Aunque se entre y se vea o elimine la notificación, el número es constante y jamás desaparece.

**Comment by rafgardom** [comment]
Asigno la incidencia a Diego que se encargará de pintar el numerito según el número de notificaciones que haya y a Santi para que diego le indique qué necesita exactamente que le llegue a la vista (supongo que será suficiente con el número de notificaciones que tenga ese actor.

Aquí surgen 2 problemas:
       * Tal cual está no podemos conocer si una notificación ha sido leída por un actor. Esto se soluciona añadiendo un atributo isRead.

       * El atributo isRead no valdría para las notificaciones globales ya que éstas se envían a todos los usuarios o a varios con lo que no hay una notificación global por cada usuario sino una solo para todos ellos. En el momento que se marque como isRead por parte de un usuario, se marcaría para todos los demás. Este problema sólo se resuelve cambiando la relación a OneToMany (una notificación sólo tiene un usuario y por tanto, para las notificaciones globales habría que crear una por cada uno de los usuarios que hay en el sistema. Creo que esta opción es la más acertada además se podría añadir un botón para eliminar la notificación si el usuario lo quiere).

**Comment by sanframar** [comment]
Se ha implementado el nuevo sistema de notificaciones. Además, ahora cuando un usuario lee una notificación el número de notificaciones sin leer disminuye.
