### ISSUE TITLE
Cantidad en el pago Paypal incorrecta

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#130]
Si realizamos el pago de una oferta a través de paypal nos damos cuenta que la cantidad a pagar es un dígito menor que lo reflejado en nuestra aplicación.

![1](https://user-images.githubusercontent.com/10712481/39207043-438ea76e-47ff-11e8-9f19-1c0525f1dcb1.PNG)

![imagen](https://user-images.githubusercontent.com/10712481/39207054-485df678-47ff-11e8-8fee-53a888df62a2.png)

**Comment by rafgardom** [comment]
Lo que paypal cobra es la comision que nosotros nos llevamos, que actualmente es el 10%
