### ISSUE TITLE
Validación incorrecta en la creación de viajes

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#133]
Desde el rol de professional, al crear un nuevo viaje nos aparece un mensaje de error al insertar tildes en los campos obligatorios.
![imagen](https://user-images.githubusercontent.com/10712481/39207824-4c6651b4-4801-11e8-8ded-32611be68342.png)

Además, como mejora, se podría poner el campo de fecha como en otros formularios, de tal forma que aparezca el calendario y el usuario pueda hacer click de forma dinámica en la fecha, sin necesidad de escribirla manualmente.

**Comment by ecameroruiz** [comment]
Se va a eliminar el rol de professional por lo tanto se cierra esta issue.
