### ISSUE TITLE
¿ "Mis Viajes pasados" crece hasta el infinito ?

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#136]
Desde el rol de professional, si visualizamos la lista de viajes pasados, vemos que existe la opción de eliminarlos. ¿esta lista crece hasta el infinito? ¿existe alguna forma de eliminarlo?

Creo que se debería de limitar el tamaño de esta lista de una forma u otra, ya que esto con el tiempo provocaría una gran cantidad de datos basura en la BD.

**Comment by rafgardom** [comment]
El rol de professional ya no existe así que se cierra la incidencia
