### ISSUE TITLE
Error al aportar puntuación a un viaje

### ISSUE THREAD

**Issue by rafgardom** [rafgardom/ISPP-Makai#138]
No deja crear un rating de un viaje, en este caso de uno ya pasado:

![imagen](https://user-images.githubusercontent.com/22836350/39237862-ffa3828a-487c-11e8-91f1-c2df8b94f4f3.png)

![imagen](https://user-images.githubusercontent.com/22836350/39237875-0c4c936e-487d-11e8-96a2-25e483cc6eb9.png)

**Comment by jesvazarg** [comment]
El problema era que no te dejaba votar si solo ha asistido tu mascota al viaje, por lo que ya se permite votar.
