### ISSUE TITLE
Cuadro naranja/carne confunde

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#14]
No se si os pasa lo mismo, pero el color naranja / carne de la aplicación donde se muestra toda la info parece más bien un mensaje de error. En cuanto te llevas un par de minutos en la aplicación molesta un poco a la vista. 
Yo quitaría ese cuadro y dejaria simplemente el color de fondo verde sin más, es decir, que no se viese ninguna diferencia entre el contenido mostrado y el fondo de toda la aplicación.
Por otro lado, yo dejaría fijo en la parte inferior la sub-sección de copyright, y no que se vaya bajando según el tamaño del cuadro.

**Comment by dierodfer** [comment]
Ya se cambio por un tono gris
