### ISSUE TITLE
No aparece calendario en creación de animal

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#142]
Durante la creación de un nuevo animal, no aparece el calendario desplegable que permite elegir la fecha de forma dinámica, sin tener que escribir manualmente la fecha.

![imagen](https://user-images.githubusercontent.com/10712481/39321112-5ea36bce-4986-11e8-96d3-41e33517daca.png)

**Comment by dierodfer** [comment]
Quedo solucionado en mi ultimo commit
