### ISSUE TITLE
Validación incorrecta de fecha de nacimiento en animales

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#144]
Tanto en la creación como en la edición de animales, si insertamos una fecha de nacimiento futura, la aplicación crea el animal sin problemas, cuando no debería de permitirse estos valores futuros.

Además, si se inserta el año en formato corto (26/04/18), la aplicación rellena en año con 0s, almacenando finalmente como fecha 26/04/0018.
![imagen](https://user-images.githubusercontent.com/10712481/39321474-778b5d12-4987-11e8-9bbd-1853dc26bd45.png)

**Comment by dierodfer** [comment]
se añadió el uso de datepicker y no deja añadir otro valor que se ajuste al pattern aunque estaria bien saber de donde viene ese error

**Comment by jesvazarg** [comment]
Acabo de solucionar esta ISSUE y explico que he hecho en la ISSUE #145
