### ISSUE TITLE
Duplicidad de opciones en interfaz gráfica

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#149]
Durante la navegabilidad en la aplicación, si nos dirigimos al inicio de un rol, aparecen las opciones disponibles (solicitudes, animales, viajes, etc). Si pulsamos en una de ellas, nos dirigimso a una vista donde se muestras las opciones de esa sección. Sin embargo, sigue apareciendo esas mismas opciones en la toolbar. 
Por ejemplo, animal:

![imagen](https://user-images.githubusercontent.com/10712481/39367297-9f96a582-4a36-11e8-9ad8-91555271f96e.png)

Creo que se deberían eliminar las opciones del desplegable de la toolbar, y que simplemente fuese un botón que llevase a la vista principal donde aparecerían todas las distintas acciones de la sección, igual que si pulsasemos el botón de inicio.

**Comment by dierodfer** [comment]
Este error estaba ya solucionado parece ser un error de cache del servidor
