### ISSUE TITLE
Optimizar de tablas

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#153]
Tras realizar algunas pruebas, creo que se podría mejorar la representación de los datos en las tablas.

![imagen](https://user-images.githubusercontent.com/10712481/39471364-1c363512-4d43-11e8-8206-af75e7272be4.png)

- Si no existe imagen o no se puede representar, deberiamos de mostrar un icono / imagen genérica, y no un cuadrado con un "No se puede mostrar la imagen".
- Si los campos superan un cierto número de caracteres, debería de cortarse para su representación. De esta forma evitamos que la tabla crezca demasiado y rompa el equilibrio de la web. Otra posible solución sería limitar el tamaño de la columna, y si el campo tiene muchos caracteres, aumentar el tamaño de la fila hacia abajo.

**Comment by dierodfer** [comment]
corregido hace ya unos commits
