### ISSUE TITLE
Fallo en visualización de rating

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#156]
Al valor un usuario, las estrellas de puntuación estan superpuestas a los botones de guardar y cancelar.

![imagen](https://user-images.githubusercontent.com/10712481/39472608-bb6794d0-4d4a-11e8-8227-f2ad4e71c388.png)

Además, si modificamos el campo superior de comentario, el campo de puntuación se desconfigura más aún.

![imagen](https://user-images.githubusercontent.com/10712481/39472682-2c3257ea-4d4b-11e8-8224-94076b62165c.png)

**Comment by dierodfer** [comment]
se cambio el estilo de la vista ahora las estrellas aparecen en primer lugar y centradas ahora aprovecha mas el espacio, aunque sigue pasando cuando la pantalla es muy muy pequeña
