### ISSUE TITLE
Redirección incorrecta en rating

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#157]
Desde la vista de solicitudes, si accedemos a puntuar a otro usuario y acto seguido pulsamos en cancelar, la aplicación nos redirige a la vista de "Mis Viajes", y no a la "lista de ofertas".
Puesto que al rating se puede acceder desde viajes o desde solicitudes, una posible solución sería almacenar de alguna forma desde donde se esta accediendo al rating, si se esta haciendo desde solicitudes o desde viajes, y partiendo de esto, volver a una vista u otra.

**Comment by jesvazarg** [comment]
Ahora ya redirige bien el boton cancelar segun por donde has entrado en la votación comprobandolo con la requestUri
