### ISSUE TITLE
Se permite la puntuación repetida de un mismo usuario

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#158]
La aplicación no controla el acceso a la puntuación de usuarios ya puntuados. Si aceptamos una oferta de un trainer y acto seguido accedemos a la lista de ofertas para puntuar al usuario, podemos acceder a la vista de rating y hacer la valoración infinitas veces.

**Comment by sanframar** [comment]
Ahora no se permite votar mas de una vez.
