### ISSUE TITLE
Validación incorrecta de imagen al editar usuario

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#170]
Al editar el perfil de un usuario, si insertamos un fichero con una extensión distinta a las permitidas, la aplicación no muestra ningún error y almacena del fichero en BD. También permite incluir imagenes de tamaño mayor al permitido.

**Comment by martus13** [comment]
Arreglado en el commit 6e99830eebd5daa2fc134305a9fb4772123301c7
