### ISSUE TITLE
Error poco descriptivo en travel

### ISSUE THREAD

**Issue by dierodfer** [rafgardom/ISPP-Makai#174]
Cuando no se selecciona el tipo de animal el error es general, se debería de especificar el error.
Ademas no se traduce correctamente como aparece en la imagen.
![captura](https://user-images.githubusercontent.com/32866881/39586439-55c502a8-4ef7-11e8-8f76-bd60808395be.PNG)

**Comment by rafgardom** [comment]
Corregido 2b580765ffe2109c5fc4020fd636abefc07f4c46
