### ISSUE TITLE
Error en la creación de viaje

### ISSUE THREAD

**Issue by dierodfer** [rafgardom/ISPP-Makai#175]
Estoy obligado a elegir tipo de animal que quiero llevar, aunque no tenga sitio para animales. Es decir solo tengo sitios para humanos y tengo que elegir tipo de animal.
Se debería obligar a elegir el tipo de animal si y solo si tiene sitio para animales>0

**Comment by rafgardom** [comment]
Es obligatorio que haya hueco para un animal ya que no hacemos un servicio similar a BlaBlaCar (solo transporte de personas) con lo que mínimo debe haber hueco para un animal.
