### ISSUE TITLE
Botón sin utilidad en la vista de Hitos desde cliente

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#184]
Si accedemos a la lista de hitos desde un cliente, nos aparecen lo siguiente:

![imagen](https://user-images.githubusercontent.com/10712481/39830657-6835d47e-53c2-11e8-9d5c-47b08e86b13b.png)

Sin embargo, si intentamos editar un hito, la aplicación nos dice que no tenemos acceso al recurso:

![imagen](https://user-images.githubusercontent.com/10712481/39830704-8604442c-53c2-11e8-8807-d6c66a338f4c.png)

Lo mismo pasa si intentamos eliminar el hito.
Se deberian eliminar aquellos botones que no pueden ser utilizados por el perfil que accede.

**Comment by sanframar** [comment]
Ahora el usuario con el rol de customer no puede ver los botones de eliminar y editar un hito.
