### ISSUE TITLE
Denegación de acceso a recursos

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#185]
Desde el rol de entrenador, si nos dirigimos a la ventana de inicio:

![imagen](https://user-images.githubusercontent.com/10712481/39831464-ddbd7a06-53c4-11e8-98a7-25d47d77211e.png)

Luego pulsamos en "Mis ofertas pendientes" o en "Mis ofertas pasadas"

![imagen](https://user-images.githubusercontent.com/10712481/39831488-f3323232-53c4-11e8-9f6c-da42c4452711.png)

![imagen](https://user-images.githubusercontent.com/10712481/39831498-fc13ec7e-53c4-11e8-9954-1c37b46886d0.png)

Y luego pulsamos en el botón "volver", la aplicación nos niega el acceso:

![imagen](https://user-images.githubusercontent.com/10712481/39831521-139e1374-53c5-11e8-99f2-6e8727d7968d.png)

Se debería comprobar si este error se produce tambien en el resto de roles.
Sospecho que el problema se encuentra en la ruta a la que se intenta retroceder, ya que la prueba la he realizado desde un perfil de entrenador, y la URL que aparece al denegarme el acceso es:

`http://localhost/Makai/request/customer/myList.do`

Es decir, parece que intenta acceder a un recurso de customer desde un rol de entrenador.

**Comment by sanframar** [comment]
Ahora el sistema redirige correctamente.
