### ISSUE TITLE
Fallo al cargar imagen de banner

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#186]
Durante la creación de un nuevo banner desde un perfil de anunciante, si intentamos cargar una imagen con los requisitos que nos piden (la prueba realizada ha sido con un banner de 1000 x 130 pixeles), sigue mostrandose el error de que elancho y alto de la imagen no es correcto.

![imagen](https://user-images.githubusercontent.com/10712481/39832189-d33f4e72-53c6-11e8-825f-e05a774d5631.png)

La imagen usada para la prueba es la siguiente:

![imagen](https://user-images.githubusercontent.com/10712481/39832173-cbb8fcc0-53c6-11e8-8412-5af4be5ad3d2.png)

**Comment by sanframar** [comment]
No consigo reproducir el error.
Tal y como se puede observar en la primera captura la imagen tiene las dimensiones 1000x130 pixeles.
No obstante me he encontrado el problema de que al descargar la imagen también me ha descargado otra con un tamaño de 600x78 pixeles. Si en lugar de elegir la primera imagen, elegimos esta última el sistema muestra un error de tamaño.

![image](https://user-images.githubusercontent.com/22940989/39838615-2b00f3e6-53da-11e8-9674-6c5e0c71cee0.png)

![image](https://user-images.githubusercontent.com/22940989/39838624-32b7e978-53da-11e8-8346-65a49da1c192.png)

![image](https://user-images.githubusercontent.com/22940989/39838643-3e4752c4-53da-11e8-8312-6f39c8da4b44.png)

**Comment by rafgardom** [comment]
Efectivamente las imagenes descargadas de google no siempre tienen las medidas que ponen. He intentado reproducir el error y no lo consigo con lo que paso a cerrar la incidencia
