### ISSUE TITLE
Listado de ofertas pendientes incorrecto

### ISSUE THREAD

**Issue by martus13** [rafgardom/ISPP-Makai#189]
Al hacer seleccionar la opción "Mis ofertas pendientes" en el menú principal logueado como entrenador, se muestran también las ofertas que ya han sido aceptadas.
![image](https://user-images.githubusercontent.com/26342707/39865469-49ba5d72-544d-11e8-9447-8e23e28e9b94.png)

**Comment by sanframar** [comment]
Ahora se muetran las ofertas activas.
