### ISSUE TITLE
Campos de fechas

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#22]
Los campos de fechas, como las que aparecen en el registro de los viajes (comienzo y fin) deberían ser un poco más intuitivas, ya que no se dice en ningún sitio el formato a seguir ni las restricciones.
Yo sustituiría ese campo por alguna de estas 2 alternativas:

- Poner 3 campos (en caso de que unicamente se necesite la fecha y no la hora). Uno para el día, otro para el mes y otro para el año.

- Poner el típico icono de calendario que al pulsarlo muestra un calendario donde se puede seleccionar la fecha.

**Comment by rafgardom** [comment]
Aquí se va a implementar un datepicker. De momento se deja así para corregir antes los bugs

**Comment by dierodfer** [comment]
solucionado el datepicker es funcional y estable
