### ISSUE TITLE
¿Eliminar animal?

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#23]
No se puede eliminar los animales creados, solo se muestran. No se si esto es algo que esta pendiente de implementarse, se ha pasado por alto o alguna otra cosa, pero debería de habilitarse esta opción.

**Comment by rafgardom** [comment]
Los animales no se eliminan nunca, simplemente se ocultan activando el boolean "isHidden" pero debería haber una opción "eliminar" para ocultarlo

**Comment by shelux** [comment]
Se ha añadido un botón de eliminación, para que se oculte el animal, al modificar la propiedad "isHidden".
