### ISSUE TITLE
Credenciales en texto plano

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#24]
Los credenciales del usuario al registrarse (usuario y contraseña) se envian en texto plano, sin cifrar. Haciendo una simple prueba con el wireshark he obtenido el usuario y contraseña con el que estaba logeandome. Esto es un fallo importante a solventar desde el punto de vista de la seguridad, ya que cualquier sniffer podría capturar nuestros credenciales.

![imagen](https://user-images.githubusercontent.com/10712481/37795192-1003c2bc-2e14-11e8-8a1f-8b3b2859b8f1.png)

**Comment by rafgardom** [comment]
Se ha configurado una conexion segura (TLS-HTTPS) funcional para desplegarla cuando sea necesario. 
El certificado emitido es autofirmado ya que de momento no se ha comprado la certificación
