### ISSUE TITLE
¿Tiene sentido permitir crear viajes con 0 asientos disponibles?

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#32]
Tal y como se tiene planteado ahora la creación de viajes, se pueden crear nuevos viajes con 0 asientos. Desde mi punto de vista, este campo debería de evolucionar para pasar a ser obligatorio y mayor estricto que 0.

**Comment by ecameroruiz** [comment]
Hecho. Ahora mismo si se crea un viaje que tenga 0 asientos tanto para personas como para animales te sale un error y no te deja, tiene que haber minimo 1 asiento disponible (para persona o para mascota)
