### ISSUE TITLE
Centrar columna en listado de viajes

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#33]
Cuando se visualiza la lista de viajes, las dos columnas de "asientos para animales" y "asientos para personas" se ven alineadas a la derecha y puede llevar a confusión ya que no queda claro que número pertenece a que columna. 
![imagen](https://user-images.githubusercontent.com/10712481/37924405-11f1c404-3132-11e8-84a4-2cb22ae35105.png)

**Comment by dierodfer** [comment]
Arreglado en el commit 80b2558c54776e09587b2bcb29e74aacd5976650 , se centraron todas las columnas de todas las listas del sistema. Parece que quedaba bien en las demás tablas, se quedará así si no surgiese otro impedimento.
