### ISSUE TITLE
Información perdida al registrar / mostrar animal

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#34]
Mientras se esta registrando un animal, se pide al usuario la raza y la especie del animal. Sin embargo, al mostrar dicho animal, no aparece esta información. 
He echado un vistazo por encima en la BD y parece que dichos campos no son persistidos. Sea como sea, la información de raza y especie debe de mostrarse al usuario.

**Comment by rafgardom** [comment]
Si se persisten pero al tratarse de un enumerado, se almacenan como un entero

**Comment by shelux** [comment]
Solucionado: Se muestran las razas y las especies en el display de cada animal
