### ISSUE TITLE
No se puede modificar y/o eliminar animales

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#36]
Actualmente, la aplicación unicamente permite la creación y listado de animales, pero no existe una opción para eliminarlo y/o modificarlo.

**Comment by rafgardom** [comment]
Los animales en realidad no se borran sino que se ocultan (con el parámetro isHidden)

**Comment by gh-jvr** [comment]
tanto si se eliminan como si se ocultan, debe aparecer una opción "eliminar" para que el usuario pueda "eliminar" (aunque por dentrás no se eliminen realmente).

**Comment by shelux** [comment]
Se han añadido los botones delete y edit para solventar la issue.
