### ISSUE TITLE
Tamaño de campo demasiado pequeño en Solicitud

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#37]
Al intentar crear una nueva solicitud, los campos ""Descripción" y "Etiquetas" tienen un tamaño demasiado pequeño. Además, cuando se insertan demasiado caracteres, el error que aparece es genérico y no informa al usuario del error real.

![imagen](https://user-images.githubusercontent.com/10712481/37984667-26db2a8e-31f7-11e8-9e44-683a8226a18f.png)

Desde mi punto de vista, se deberian hacer 2 cosas:

1. Ampliar el campo para que acepte una mayor longitud, tanto en descripción como en etiquetas.
2. Añadir una validación para que se muestre un error justo debajo del campo informando del tamaño máximo permitido de caracteres en caso de que se sobrepase dicho límite.

**Comment by rafgardom** [comment]
El campo de texto se amplia cambiando la etiqueta por text-area. La validación hay que controlarla en el servicio

**Comment by jesvazarg** [comment]
Se ha cambiado el dominio para que admita hasta 2000 caracteres y se ha limitado también para que no se pueda escribir más, pero ¿se debe de indicar que el máximo es 2000 de alguna manera?

**Comment by gh-jvr** [comment]
Se sigue produciendo el error, pero esta vez solo afecta al campo "Etiquetas". Tambien se debería tanto ampliar como limitar el número de caracteres del campo.

![imagen](https://user-images.githubusercontent.com/10712481/38143118-5a905a12-343f-11e8-98d1-ee62675aa88f.png)

Además, respondiendo a la pregunta de Jesús del último comentario, yo creo que si no se permite escribir más de 2000 caracteres, no es necesario mostrar ningún mensaje de error, ya que este limite jamás podrá ser superado y por tanto el error jamás se mostrará. 
Para solucionar el problema de "etiquetas" se puede tomar una de las dos posibles soluciones: 
-  Mostrar un mensaje de error diciendo que se ha superado el límite máximo de caracteres permitidos.

- No permitir escribir más de X caracteres.
Ambas soluciones son buenas y validas (pero excluyentes, no se debería de aplicar las dos a la vez).

**Comment by jesvazarg** [comment]
Se ha puesto un limite de 100 caracteres en los tags en el commit 
457b98d
