### ISSUE TITLE
Listas infinitas

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#39]
Las listas de elementos que se muestras no tienen un limite, es decir, si existen 1000 elementos, aparecen los 1000 en la misma vista, con un scroll minusculo. Esto lo he visto en Solicitudes, pero probablemente suceda en todas las vistas de listar de la aplicación.
Sería recomendable poner un número máximo de items por página, y que el usuario pueda ir pasando de una página a otra. Un buen número de elementos por página sería 10, aunque está abierto a debate.

![imagen](https://user-images.githubusercontent.com/10712481/37986838-df8db312-31fc-11e8-8763-06af2e0a109f.png)

**Comment by rafgardom** [comment]
Se lo asigno a Diego que mire las tablas de bootstrap. Dejo también un enlace de referencia que me ayudó para hacer tablas dinámicas en python: 
https://editor.datatables.net/examples/styling/bootstrap

**Comment by dierodfer** [comment]
Arreglado, se tomó la solución temporal de usar la paginación ofrecida por jstl. Fueron adaptadas todas las listas del sistema. Se debería testear el correcto funcionamiento de la paginación de todas las tablas.
