### ISSUE TITLE
Eliminar solicitud no funciona correctamente

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#40]
Cuando se quiere eliminar una solicitud de la lista de solicitudes, siempre se elimina la primera solicitud de la lista, independientemente de la solicitud seleccionada. 
Probablemente este fallo se produzca por una mala gestión de los IDs de los items a eliminar.

**Comment by jesvazarg** [comment]
Se ha arreglado el tag del delete para que capte el id del objeto a borrar
