### ISSUE TITLE
Campo obligatorio "Precio" sin validación

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#42]
Si desde el tipo de usuario "entrenador" intentamos crear una oferta nueva para una solicitud recibida y dejamos todos los campos vacíos, el campo obligatorio "precio" no tiene ningún mensaje de error, siendo éste obligatorio.

![imagen](https://user-images.githubusercontent.com/10712481/37987972-f6b929ba-31ff-11e8-87e9-4763fc8ce6a4.png)

**Comment by dierodfer** [comment]
Creo que este problema se soluciono con mi ultimo commit 8dcba30355b4b7e732cf5deba73db6df8633bb98 . Recomiendo que se vuelva a testear.

**Comment by jesvazarg** [comment]
Con el nuevo estilo para el precio no puedes escribir un precio en concreto, por lo que no es muy útil una barra así sin un input

**Comment by dierodfer** [comment]
Este bug se arreglo en el issue #82 el valor es optativo y se guarda como 0 no como null
