### ISSUE TITLE
Error sin descripción al insertar demasiado caracteres

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#44]
Al crear una nueva oferta desde el perfil de entrenador, si insertamos una gran cantidad de caracteres en los campos y creamos la oferta, la aplicación no nos deja crearla y nos aparece como único mensaje descriptivo "Error".

![imagen](https://user-images.githubusercontent.com/10712481/37988658-c536c4cc-3201-11e8-9e9c-e93428f52ab9.png)

Como posible solución, se podría mostrar debajo de cada campo un mensaje de error informando del tamaño máximo de ese campo en concreto, dando así más información del error al usuario.

**Comment by martus13** [comment]
Ya salen los errores indicando el tamaño máximo permitido. Además en el textarea se indica el numero máximo y cuantos se llevan escritos:
![captura](https://user-images.githubusercontent.com/26342707/38165806-c6bb9dd4-3519-11e8-9cd2-f01358645dd6.PNG)
