### ISSUE TITLE
No se comprueba las fechas de inicio y fin en viajes

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#50]
Si intentamos crear un viaje e insertamos una fecha de fin de viaje posterior a la fecha de inicio del viaje, la aplicación nos lo acepta sin ningún problema. Este tipo de comportamiento no lo deberiamos de permitir ya que no tiene sentido terminar un viaje antes de que comience.

![imagen](https://user-images.githubusercontent.com/10712481/38141938-b6e606a4-343a-11e8-8c66-1c65bb8fdf97.png)

![imagen](https://user-images.githubusercontent.com/10712481/38142032-18100ee8-343b-11e8-9e35-55069d98297c.png)

**Comment by ecameroruiz** [comment]
Ya no se puede crear/editar viajes si la fecha de inicio es posterior a la de fin. También he hecho que se muestren en los lists solo los viajes que no han pasado (porque no tendría sentido modificar/eliminar viajes que ya se han realizado). Falta solo mostrar el mensaje de error, lo pondré cuando termine otras modificaciones que tengo que hacer en el controlador.
