### ISSUE TITLE
Mensaje de confirmación con letras en blanco

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#51]
Cuando eliminamos cualquier elemento en la aplicación nos aparece un cuadro de confirmación. Dicho cuadro contiene un texto con letras en blanco, que no se distinguen del fondo blanco.

![imagen](https://user-images.githubusercontent.com/10712481/38142162-a1f70b70-343b-11e8-81f5-d16f79270d61.png)

![imagen](https://user-images.githubusercontent.com/10712481/38142171-ab73154a-343b-11e8-9a07-78ca42c9c72b.png)

Esto pasa, al menos, en solicitudes y en viajes, aunque probablemente pasará lo mismo en el resto de la aplicación.

**Comment by dierodfer** [comment]
Arreglado se cambio el color a gris
