### ISSUE TITLE
Redirección a vista vacía al intentar ver "tratos" de una solicitud no aceptada

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#56]
Si creamos una solicitud y acto seguido (sin que esta solicitud haya sido aceptada) le damos al botón "tratos", la aplicación nos redirige a una vista vacía.
No se exactamente si este es el funcionamiento deseado, pero lo veo un poco confuso de cada al usuario.

![imagen](https://user-images.githubusercontent.com/10712481/38143781-5a578d10-3442-11e8-98be-ae0d69081295.png)

Desde mi punto de vista, yo mostraría un error en pantalla (igual que aparece un mensaje de confirmación al eliminar un elemento), informando al usuario que la oferta aun no ha sido aceptada por ningún entrenador.

**Comment by dierodfer** [comment]
desde mi punto de vista yo desactivaría el link que lleva a esa vista en el caso de no tener ninguna oferta.

**Comment by jesvazarg** [comment]
Ya no muestra el botón si no hay ofertas asignadas a la request
