### ISSUE TITLE
Campo "precio" extraño

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#57]
Si nos registramos como entrenador e intentamos responder con una oferta a una solicitud  que hemos recibido, al insertar el precio de la oferta, tenemos el siguiente campo:
![imagen](https://user-images.githubusercontent.com/10712481/38143897-d8c65ac8-3442-11e8-81f5-5fae145878e8.png)
Es cierto que puede considerarse innovador, pero desde mi perspectiva, lo veo un poco extraño de cara a la usabilidad del usuario medio. ¿Que pasa si quiero poner como precio una cantidad mayor a 4000€?¿Y si quiero poner 3500,67€?
Creo que se debería dejar un campo númerico simple, donde el usuario pueda insertar manualmente el precio que desee.

**Comment by rafgardom** [comment]
Dijimos que la barra solo iba a implementarse para los enteros, los reales es mejor que se introduzcan a mano

**Comment by dierodfer** [comment]
Se elimino el slider en precio y se dejo como estaba y se le añadio ala duración
