### ISSUE TITLE
Mensaje de error poco descriptivo en modificación de oferta

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#59]
Si desde un usuario entrenador intentamos modificar una oferta justo al mismo tiempo que el customer a aceptado esta misma oferta, se muestra como mensaje de error unicamente "error". Creo que se debería de informar al usuario que dicha modificación no es posible porque el customer ya ha aceptado la oferta.

![imagen](https://user-images.githubusercontent.com/10712481/38144286-60a8065c-3444-11e8-83d1-3fa6c08816dd.png)

La prueba que he realizado ha sido:

1. He abierto 2 ventanas en el navegador, una de ellas en modo privado.
2. He accedido al usuario "customer" con una de las ventanas y al usuario "entrenador" con la otra ventana.
3. Desde customer, he creado una solicitud nueva.
4. Desde entrenador he enviado una oferta a esa solicitud.
5. Antes de aceptar la oferta desde customer, he accedido a modificar la oferta desde el perfil de entrenador, he modificado el precio pero he dejado la vista en ese punto, sin pulsar en guardar cambios.
6. Desde customer he aceptado la oferta.
7. Desde entrenador, sin recargar la vista, pulso en guardar cambios.

**Comment by sanframar** [comment]
Ahora el sistema muestra un error más descriptivo.
> f185190b246d57d030c37e957a8888569b62c3ab

![offer](https://user-images.githubusercontent.com/22940989/38148930-c6128d8c-3458-11e8-82be-cc65ea54f6e1.PNG)
