### ISSUE TITLE
No se pueden crear Viajes

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#60]
Cuando intentamos crear un viaje desde Customer, la aplicación nos devuelve un error y no  nos permite finalizar el proceso de creación.

![imagen](https://user-images.githubusercontent.com/10712481/38161737-3b5bd680-34d5-11e8-9e68-0d2e7db3ff64.png)

**Comment by ecameroruiz** [comment]
Había un error en la implementación de Coordinates (para los campos de origin/destination) que estaba causando fallos en la creación de viajes (incluyendo lo del panic con campos vacíos)
