### ISSUE TITLE
No se notifica a entrenador las nuevas solicitudes

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#62]
Si desde el perfil de customer creamos una nueva solicitud, al entrenador le llega la solicitud (le aparece en su lista de solicitudes) pero no le llega ninguna notificación al respecto.

**Comment by martus13** [comment]
Esto funciona correctamente, pero se debe tener en cuenta que las notificaciones sólo se envían a los entrenadores que tengan el entrenamiento adecuado.
