### ISSUE TITLE
¿No se permite eliminar notificaciones no-leidas?

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#63]
El botón de eliminar notificación no aparece hasta que no hemos visto la notificación. ¿Este es el comportamiento deseado? ¿Vamos a forzar a un usuario a ver una notificación para poder eliminarla de su lista?.
 Desde mi punto de vista, esto es un poco intrusivo para el usuario, ¿Os imaginais que no nos permitiesen eliminar correos sin antes abrirlo?.

**Comment by sanframar** [comment]
Ahora una notificación se puede eliminar sin necesidad de leerla.
