### ISSUE TITLE
Se permite acceder a una solicitud eliminada

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#64]
Desde el perfil de customer, la aplicación permite acceder a solicitudes ya eliminadas mediante URL.
Prueba realizada:
1. He creado una nueva solicitud desde Customer
2. He accedido a la solicitud y he copiado la url de la solicitud, donde aparece el ID del objeto
3. He vuelto atrás y he eliminado la solicitud
4. He introducido la url en el navegador y la aplicación me ha mostrado son problemas la solicitud eliminada.

**Comment by jesvazarg** [comment]
Este bug ocurre cuando tiene una oferta nueva aceptada porque aún no se genera los Receipts.
En cuando se hayan creado los Receipts cuando se acepte una oferta debería de funcionar.
Se deberá de comprobar cuando esté esa parte funcionando

**Comment by jesvazarg** [comment]
Ya no se muestra las Request borradas, ya que se borran todas realmente. Este cambio se ha realizado al borrarse Receipt en el commit 5fac9f8 con sus mdificaciones para que siga funcionando.
