### ISSUE TITLE
Aceptar en paralelo varias ofertas

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#66]
Desde el usuario customer, si recibimos varios ofertas para una misma solicitud y aceptamos ambas en paralelo (desde una ventana de incognito), la aplicación no nos devuelve ningún error al aceptar la segunda oferta (aunque es cierto que se queda con la primera que fue aceptada).

Prueba realizada:
1. Accedo al usuario Customer desde dos vetanas del navegador, una de ellas en modo privado.
2. visualizamos una solicitud con varias ofertas en ambas ventanas.
3. Aceptamos una oferta en una de las ventanas y acpetamos la otra desde la otra ventana (sin recargar la pagina).

Creo que el bug se solucionaría comprobando si ya hay alguna oferta aceptada antes de aceptarla, y en caso afirmativo, mostrar un mensaje de error y devolviendo al usuario a la vista donde se muestran todas las solicitudes.

**Comment by sanframar** [comment]
Ahora el sistema muestra un error.

![error](https://user-images.githubusercontent.com/22940989/38172955-f1ebf58e-35b5-11e8-9965-214ad31534f9.PNG)
