### ISSUE TITLE
Mejora en notificaciones: eliminar todas

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#67]
A medida que he ido haciendo pruebas, me he encontrado con que tenia 17 notificaciones para un usuario, y para poder eliminarlas, he tenido que ir una por una. ¿Sería asequible desde el punto de vista del desarrollo añadir un botón abajo del todo "eliminar todas" o algo así, que quiten todas las notificaciones de una vez?.

Imaginad el siguiente escenario: en un futuro cercano tenemos 3000 usuarios activos, 700 de ellos entrenadores. Un customer crea una solicitud, y le responden 300 entrenadores. Al customer se le crean 300 notificaciones con las ofertas ¿creeís que el customer va a eliminar 300 notificacioens una a una, todas ellas con el mismo contenido?.

**Comment by sanframar** [comment]
Ahora se puede eliminar todas las notificaciones con un solo click.
Se debería crear un nuevo estilo para el botón de eliminar todas las notificaciones ya que ahora mismo es igual al de eliminar una notificación.

**Comment by dierodfer** [comment]
Estilado, solo realiza la verificación de eliminar cuando quieres borrar todas, individualmente no necesita verificación
