### ISSUE TITLE
Condiciones de uso

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#7]
Durante el registro de usuarios se pide que se acepten las condiciones de uso, sin embargo, no existe ningún apartado o enlace donde el usuario se pueda dirigir para leer dichas condiciones.

**Comment by rafgardom** [comment]
Le asigno la tarea a Marta que es la que estuvo revisando los competidores y la que más familiarizada puede estar con los términos de uso de nuestra aplicación por similitud a ellos.

**Comment by martus13** [comment]
Añadidas las condiciones de uso y la política de cookies en los registros de usuarios y en el footer. Además, se ha añadido una barra inferior para la política de cookies.
