### ISSUE TITLE
Tras aceptar oferta, no se eliminan las otras

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#71]
Desde un customer, si aceptamos una de las ofertas recibidas para una solicitud, el resto de ofertas recibidas para esa misma solicitud nos sigue apareciendo y nos sigue apareciendo el botón de "aceptar" (y si pulsamos nos lleva a paypal para hacer el pago).

![imagen](https://user-images.githubusercontent.com/10712481/38165805-befd6fbe-3519-11e8-8ad0-74191082bc33.png)

**Comment by sanframar** [comment]
Si se acepta una oferta y se realiza el pago, las otras ofertas son eliminadas correctamente.
