### ISSUE TITLE
Aceptar 2 ofertas para un mismo animal en el mismo periodo de tiempo

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#72]
Actualmente, el sistema permite crear 2 solicitudes distintas para un mismo animal (hasta aquí no hay problema). La palicación tambien permite la creación y aceptación de ofertas para estas dos distintas ofertas con un mismo animal, de tal modo que las fechas se solapan. 
Esto no tiene sentido ya que un mismo animal no va a estar recibiendo 2 entrenamientos simultaneos.

Desde mi punto de vista, creo que se deberían evitar este tipo de incongruencias reservando al animal durante el timpo de entrenamiento. Una posible solución podría ser añadir un campo en BD que sea la fecha en la que el animal termina su entrenamiento (y queda libre para comenzar otro), de este modo, cada vez que se quiera crear una nueva oferta y/o aceptar dicha oferta, primero se debe comprobar si la fecha de entremiento de la nueva oferta es posterior a la almacenada en BD (en otras palabras, comprobar si el animal esta disponible en ese periodo de tiempo).

**Comment by sanframar** [comment]
Ahora mismo cuando se acepta una offer el atributo de Animal llamado finishTraining es actualizado. Faltaria filtrar los animals que una offer puede tener.

**Comment by gh-jvr** [comment]
Cuando se intenta aceptar una oferta para un animal que previamente ya ha sido aceptado en otra oferta (para una misma solicitud), la aplicación permite el pago para esa oferta. 
La prueba que he realizado ha sido:
1. He creado 2 ofertas para una misma solicitud.
2. He aceptado una oferta (pasando por todo el proceso de pago).
3. Desde una ventana privada, he intentado aceptar la otra oferta, y la aplicaicón me ha redireccionado a paypal.

Este comportamiento no se debería permitir ya que un mismo animal no puede estar en 2 ofertas en paralelo.
