### ISSUE TITLE
No se tabula los textos muy grandes

### ISSUE THREAD

**Issue by jesvazarg** [rafgardom/ISPP-Makai#74]
Si se crea un texto muy grande y se visualiza, tienes que mover el navegador con el scrollback hacia el lado para poder ver todo el texto al completo.
Esto se puede comprobar por ejemplo cuando se visualiza una Request con una descripción muy grande.
![image](https://user-images.githubusercontent.com/26336058/38166111-9879cc02-351e-11e8-81df-3a0aa2e82baa.png)

**Comment by dierodfer** [comment]
Las vistas display aun no están estiladas cuando se estilen este problema desaparecerá.

**Comment by dierodfer** [comment]
ya se estiló el display de actor en mi ultimo commit e82699ccb6bf4900273f9d8c6d750a428111fdb6 y se tabulan ala perfección.
