### ISSUE TITLE
Información adicional en Solicitudes

### ISSUE THREAD

**Issue by rafgardom** [rafgardom/ISPP-Makai#75]
Añadir al listado el nombre del cliente que crea la solicitud con un enlace a su perfil

**Comment by adrluqmon2** [comment]
Las vistas afectadas son Mis ofertas y Solicitudes del perfil de Adiestrador, es bueno tener un enlace al perfil del solicitante, el cual debería tener una foto. Ayuda a contextualizar mejor el funcionamiento personal de la aplicación ya que al fin y al cabo es una petición personal que hace una persona. Por esta misma razón, yo lo añadiría a todas las vistas que fuera necesario.

**Comment by jesvazarg** [comment]
Podré de que usuario es la Solicitud o la Oferta de cada objeto de la lista, pero aún no se puede acceder al perfil de un usuario que no sea el propio, así que de momento lo crearé con el nombre solamente

**Comment by sanframar** [comment]
Ya he implementado eso, ya se puede acceder al perfil de un usuario que no sea el tuyo.

**Comment by jesvazarg** [comment]
Ahora se ve el link de Customer y Animal en el listado y en el display
