### ISSUE TITLE
Un trainer no puede ver un animal

### ISSUE THREAD

**Issue by jesvazarg** [rafgardom/ISPP-Makai#78]
He entrado como Trainer1 y he intentado ver el perfil del Animal1 del Customer1 y no me ha dejado ver la vista.
Creo que solamente tiene permiso entrar a esa vista un customer.

![image](https://user-images.githubusercontent.com/26336058/38174078-fd234a1c-35c7-11e8-8f19-013f5a8d401d.png)

**Comment by shelux** [comment]
Solucionado, faltaba añadir Trainer a la lista de actores que podían verlo.
