### ISSUE TITLE
Estilo vistas viajes

### ISSUE THREAD

**Issue by ecameroruiz** [rafgardom/ISPP-Makai#79]
En la vista general de viajes se muestran tanto los viajes creados por el usuario como los creados por otras personas y en las vistas relativas a los viajes del usuario logueado (mis viajes y viajes pasados), se muestran también tantos los viajes creados por el usuario como viajes en los que va a participar o ha participado como pasajero. Las funcionalidades de los botones están ya limitadas según el caso, pero para que sea más visual, sería una buena idea destacar en las listas los viajes creados por el propio usuario, ya sea con un color distinto o con algún icono. 

Por otro lado, en la vista de viajes pasados, ya hay un botón habilitado para los ratings y habría que añadir un icono de una estrella o algo por el estilo. Será el mismo botón que se use para los ratings de adiestradores cuando lo implementen.

**Comment by dierodfer** [comment]
no encuentro dicho botón háblame mañana por privado y me indicas

**Comment by dierodfer** [comment]
se estilo la vista de inscribirse en un viaje
