### ISSUE TITLE
El botón de editar perfil no desaparece

### ISSUE THREAD

**Issue by dierodfer** [rafgardom/ISPP-Makai#81]
Si accedemos al perfil de otro usuario nos aparece el botón de editar perfil el cual solo debe de aparecer cuando estamos en el nuestro. Aunque parece que la funcionalidad esta bien ya que cuando le damos a editar nos envía al formulario de editar nuestro propio perfil.

**Comment by martus13** [comment]
Se controla que el actor logueado sea el mismo que el que se esta mostrando en el display, y si no es el mismo no se muestra el botón de editar.
