### ISSUE TITLE
El atributo precio en oferta no es obligatorio

### ISSUE THREAD

**Issue by dierodfer** [rafgardom/ISPP-Makai#82]
Desde mi punto de vista el atributo precio en oferta debería de ser obligatorio. Cuando se deja vacio en el formulario no se inicializa a 0 sino que recoge directamente null.
![captura](https://user-images.githubusercontent.com/32866881/38239419-f8536768-372c-11e8-870a-54c9d6525ccc.PNG)

**Comment by sanframar** [comment]
Ahora si el trainer no introduce el atributo price el sistema no lo guarda como null, en su lugar lo gurda como un 0.

![pricenotnulloffer](https://user-images.githubusercontent.com/22940989/38267043-8b43b314-377a-11e8-9d6b-ae97dc024b50.PNG)
