### ISSUE TITLE
No se puede visualizar Display de Professional

### ISSUE THREAD

**Issue by dierodfer** [rafgardom/ISPP-Makai#83]
Al intentar acceder al display de cualquier profesional desde customer, trainer o admin recoge el error  _javax.el.PropertyNotFoundException: Property 'surname' not found on type domain.Professional_
ya que la vista contiene hasAnyRole('CUSTOMER', 'ADMIN', 'TRAINER').
El código solo realiza la comprobación del actor logueado no del actor que se muestra en el display.

**Comment by martus13** [comment]
Ahora se comprueba por el actor que se está mostrando, no por el logueado.
