### ISSUE TITLE
Eliminación de animales con ofertas no aceptadas.

### ISSUE THREAD

**Issue by martus13** [rafgardom/ISPP-Makai#85]
Si un protectora elimina un animal de la base de datos que tiene ofertas relacionadas que no han sido aceptadas, se debe eliminar el animal y sus ofertas, enviando una notificación a los entrenadores afectados.

**Comment by shelux** [comment]
Se han añadido características al delete de animal para cumplir lo que se pedía en la issue, así como un método en el servicio de Offer.
