### ISSUE TITLE
PANIC al seleccionar el botón "Solicitudes" del menú

### ISSUE THREAD

**Issue by martus13** [rafgardom/ISPP-Makai#89]
Al hacer click en el botón "Solicitudes" del menú principal logueado como entrenador, sale el siguiente panic:
![image](https://user-images.githubusercontent.com/26342707/38279277-da3f6b1e-379f-11e8-89b8-c9fae0e700d9.png)

**Comment by sanframar** [comment]
Error corregido tras la ejecución del populate.
