### ISSUE TITLE
Error al seleccionar la opción "Mis ofertas" del menú

### ISSUE THREAD

**Issue by martus13** [rafgardom/ISPP-Makai#90]
Al hacer click en el botón "Mis ofertas" del menú principal logueado como entrenador, sale un error 500 con el siguiente mensaje:
![image](https://user-images.githubusercontent.com/26342707/38279355-3775995c-37a0-11e8-9c5c-1ad061179c5a.png)

**Comment by sanframar** [comment]
Error corregido tras la ejecución del populate.
