### ISSUE TITLE
Bug al inscribirse en un viaje

### ISSUE THREAD

**Issue by dierodfer** [rafgardom/ISPP-Makai#94]
Al inscribir un animal en un viaje que contiene 0 sitios disponibles para animales, no salta ningún error y persiste en la base de datos. Sin embargo funciona correctamente si introducimos más de un animal en el viaje de 0 sitios disponibles.
![captura](https://user-images.githubusercontent.com/32866881/38470562-fecac0aa-3b64-11e8-8acc-550f346beef1.PNG)

**Comment by jesvazarg** [comment]
En el caso de que te permita registrar a tu animal en ese viaje es porque ya se ha inscrito antes en ese viaje. Si después de apuntarte no llegaras a seleccionar a tu mascota, es como si lo quitaras del viaje.

Lo único que falta por implementar sería que cuando entrases a editar tu registro de viaje ya te venga seleccionado quien está ya apuntado o no en el propio checkbox.
