### ISSUE TITLE
Desplegable de categoría de una solicitud

### ISSUE THREAD

**Issue by alevazenc** [rafgardom/ISPP-Makai#95]
Al crear una solicitud como customer, en el desplegable de categoría, aunque el idioma seleccionado sea español, las categorías salen en inglés.

**Comment by jesvazarg** [comment]
Tengo la solución en local pero no puedo subirlo, en unas horas la subo.

**Comment by jesvazarg** [comment]
Se ha tenido en cuenta en todas las vistas, tanto en los formularios como en listas y display, por lo que ahora se mostrará todos los ENUMs en el idioma seleccionado.
