### ISSUE TITLE
Cuidado con quien baneas

### ISSUE THREAD

**Issue by jesvazarg** [rafgardom/ISPP-Makai#96]
Si te registras como administrador y listas a todos los usuarios, uno de ellos es el propio administrador y viene con el botón de "banear", cosa que no debería de salir en la propia lista.
Pero el mayor problema es cuando decidimos tontamente banearse a si mismo, por lo que nos quitaríamos el privilegio de poder desbanearnos o logearnos.

Por lo que habría que quitar de dicha lista al admin y habría que restringir que un admin no pueda banear a un admin.
![image](https://user-images.githubusercontent.com/26336058/38530441-cdaede5a-3c6a-11e8-857f-775d6780eeec.png)

**Comment by sanframar** [comment]
Ahora el administrador no se puede banear a si mismo y no aparece en la lista de actores a banear.
