### ISSUE TITLE
Bug en chip/animal

### ISSUE THREAD

**Issue by dierodfer** [rafgardom/ISPP-Makai#97]
Al editar un animal no se modifica el chip y le damos a guardar reconoce como ya usado, eso solo debería pasar solo a la hora de crear. Al editar debería comprobar que no existe otro chip igual en la BD, exceptuando el suyo propio. 
![captura](https://user-images.githubusercontent.com/32866881/38548640-88026b5e-3cb2-11e8-9c56-47b1429c297f.PNG)

**Comment by sanframar** [comment]
Ahora se puede editar adecuadamente un animal, y los errores son mostrados adecuadamente.
