### ISSUE TITLE
Fallo en visualización de algunas tablas

### ISSUE THREAD

**Issue by gh-jvr** [rafgardom/ISPP-Makai#99]
Algunas tablas aparecen cortadas por los laterales, como si la ventana del navegador no tuviese espacio suficiente, cuando realmente si tiene espacio.

![imagen](https://user-images.githubusercontent.com/10712481/38626678-6332b1a2-3dad-11e8-984e-f17557da3a0e.png)

Esto pasa al menos en "listar viajes" y en "mis vehiculos".

**Comment by dierodfer** [comment]
Se arreglo en mi ultimo commit 49367213e1283a977cbb9a87a7df933ae5dde212
El erro viene dado a la cantidad excesiva de información en las tablas
